### ISSUE TITLE
No provider for AngularFireAuth when lazy load module

### ISSUE THREAD

**Issue by heitorcaldeira** [module-federation/module-federation.github.io#14]
Hey guys!

I'm trying to implement Module Federation with Angular and NgRX, but i'm facing a problem and don't know how to fix it.

The problem is: when **X** application lazy loads a module from **Y** application that uses Firebase, angular does not  recognize the fireauth provider.

I have 2 apps: **Auth** and **Dashboard**.

My **Auth** application uses firebase to do user login.

The firebase request login is made by a NgRX effect:

``` lang-js
    import {AngularFireAuth} from '@angular/fire/auth';

    @Injectable()
    export class AuthEffects {
      
      userLogin$: Observable<Action> = createEffect(() => {
        /* effect implementation */
      });
      
      constructor(private fireAuth: AngularFireAuth){}
    }
```

The **AuthModule** imports:

``` lang-js
imports: [
    /* ...other imports */
    StoreModule.forFeature('authState', authReducer),
    EffectsModule.forFeature([AuthEffects]),
    AngularFireModule.initializeApp(firebaseConfig),
    AngularFireAuthModule
]
```

The **Dashboard AppRoutingModule** imports:

``` lang-js
const routes: Routes = [
  {
      path: '',
      pathMatch: 'full',
      loadChildren: () => import('auth/AuthModule').then(m => m.AuthModule)
  }
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ],
  exports: [RouterModule]
})
```

### When I start only the **Auth** application, everything works fine and I can do login. 

But when I try to use the **Auth** application remotely, inside **Dashboard** application, I get this error:

    NullInjectorError: StaticInjectorError(AppModule)[InjectionToken angularfire2.app.options]: 
      StaticInjectorError(Platform: core)[InjectionToken angularfire2.app.options]: 
        NullInjectorError: No provider for InjectionToken angularfire2.app.options!

Partial **Auth** - webpack.config.js
``` lang-js
    plugins: [
        new ModuleFederationPlugin({
          name: 'auth',
          library: {type: 'var', name: 'auth'},
          filename: 'remoteEntry.js',
          exposes: {
            './AuthModule': './src/app/login/auth.module.ts',
            './AuthComponent': './src/app/login/auth.component.ts',
            './AuthActions': './src/app/store/actions/auth.actions.ts',
            './AuthReducer': './src/app/store/reducers/auth.reducer.ts',
            './AuthEffects': './src/app/store/effects/auth.effects'
          },
          shared: {
            ...dependencies,
            '@angular/core': {
              requiredVersion: dependencies['@angular/core'],
              singleton: true,
            },
            '@angular/common': {
              requiredVersion: dependencies['@angular/common'],
              singleton: true,
            },
            '@angular/router': {
              requiredVersion: dependencies['@angular/router'],
              singleton: true,
            }
          }
        })
    ]
```

Parial **Dashboard** - webpack.config.js

``` lang-js
    plugins: [
        new ModuleFederationPlugin({
          name: 'dashboard',
          library: {type: 'var', name: 'dashboard'},
          filename: 'remoteEntry.js',
          remotes: {
            auth: 'auth',
          },
          shared: {
            ...dependencies,
            '@angular/core': {
              requiredVersion: dependencies['@angular/core'],
              singleton: true,
            },
            '@angular/common': {
              requiredVersion: dependencies['@angular/common'],
              singleton: true,
            },
            '@angular/router': {
              requiredVersion: dependencies['@angular/router'],
              singleton: true,
            }
          }
        })
      ]
```

I tried to resolve it by myself, but Module Federation is a new thing and we have little posts about.

Can someone help me? If you came until here, thank you very much! :D

**Comment by ScriptedAlchemy** [comment]
you need to share the auth module / auth provider as well - otherwise, context will not be shared as each would use its own

**Comment by heitorcaldeira** [comment]
Thanks @ScriptedAlchemy ! At first, congratulations, your plugin is awesome!

I resolved my problem creating a file called **fire.auth.ts**:
```
export {AngularFireModule} from '@angular/fire';
export {AngularFireAuthModule} from '@angular/fire/auth';
export {firebaseConfig} from '../config/firebase.config';
```
And exposing this at webpack.config.js

`'./FirebaseConfig': './src/app/config/fire.auth.ts'`

Then, my **Dashboard** module now looks like:

```
import {AngularFireModule, firebaseConfig, AngularFireAuthModule} from 'auth/FirebaseConfig';
...
...
imports: [
    AngularFireModule.initializeApp(firebaseConfig),
    AngularFireAuthModule
]
```

Now the module works fine, the component appears on the screen, but I get another error:
```
Uncaught TypeError: app.auth is not a function
    at angular-fire-auth.js
```

I think it is not something connected to module federation, so i will close the issue.

Thank you very much!

**Comment by ScriptedAlchemy** [comment]
No problem :)

**Comment by raliand** [comment]
Hey, @heitorcaldeira. I am trying to do the same, but I get an error on the AngularFireModule.initializeApp(firebaseConfig) line: "Value at position 3 in the NgModule.imports of AppModule is not a reference
  Value could not be determined statically." Where am I going wrong?
