### ISSUE TITLE
Official Module Federation Documentation?

### ISSUE THREAD

**Issue by Domiii** [module-federation/module-federation.github.io#20]
Currently, when googling for `modulefederationplugin documentation`, only guides and blog articles pop up, but there is no documentation on all parameters, which makes me nervous when considering using it in a project.

What I found:

* [Official Webpack Site explaining the concept](https://webpack.js.org/concepts/module-federation/)
* [module-federation-examples](https://github.com/module-federation/module-federation-examples)
* (after a long time of searching and reading, I stumbled across) this github.io page ([here](https://module-federation.github.io/blog/get-started))
* [your initial pitch in webpack issues](https://github.com/webpack/webpack/issues/10352)
* [the (un-?)official youtube playlist](https://www.youtube.com/watch?v=vtM0-uhYLxM&list=PLWSiF9YHHK-DqsFHGYbeAMwbd9xcZbEWJ)

All this is really really great! At the same time, when it comes down to the nitty gritty, I'd love to have some proper documentation to better understand what I am doing with all these many many parameters that I can tune :/

Any plans to explain all the things?

E.g. what does `singleton` do? Does it error out if another version of the module is found? Etc...

**Comment by lili21** [comment]
lack of docs is the biggest issue of the feature, I think. make it hard to use, and hard to understand. I would love to help.

**Comment by lili21** [comment]
https://github.com/webpack/webpack.js.org/issues/3757

**Comment by Domiii** [comment]
After looking at this website again, it looks more like the ad for a 45$ book than an attempt to produce open source documentation? I'm not arguing against open source developers getting paid for their hard work, just considering that this is probably the wrong place to ask for better API documentation?

Hopefully [lili21's comment on the webpack repo](https://github.com/webpack/webpack.js.org/issues/3757#issuecomment-735396288) gains traction.

**Comment by Domiii** [comment]
I guess I know now why I thought that this would be the right place to ask. It is because the first thing it says in the README is:

"A website documenting Webpack 5 Module Federation."

That is probably why I was expecting more that just getting shutdown here.

For anyone still ending up here: The relevant discussion on the issue is happening over at https://github.com/webpack/webpack.js.org/issues/4283.

Also, thanks @ScriptedAlchemy  for the great work on WMF. Been using it for a while now. Looking forward to that documentation still though :)

**Comment by ScriptedAlchemy** [comment]
Sorry for closing out. The site serves to aggregate stuff. 

Documentation is scarce and pull requesting the webpack docs is a strenuous process. 

I'll try to write something on this site that offers more docs, writing stuff isn't my strong suit
